// export const COLUMNS = [
//   {
//     id: "Id",
//     account_id: "Account Id",
//     exp_account_name: "exp_account_name",
//     channel_id: "channel_id",
//     channel_name: "channel_name",
//     profileId: "profileId",
//     channel_marketplace: "channel_marketplace",
//     countryCode: "countryCode",
//     channel_type: "channel_type",
//     marketPlace: "marketPlace",
//     brand_name: "brand_name",
//     brandEntityId: "brandEntityId",
//     campaignId: "campaignId",
//     amazonCampaignId: "amazonCampaignId",
//     campaign_name: "campaign_name",
//     name: "name",
//     state: "state",
//     campaignType: "campaignType",
//     targetingType: "targetingType",
//     dailyBudget: "dailyBudget",
//     campaignBudgetType: "campaignBudgetType",
//     bidding: "bidding",
//     bidding_strategy: "bidding_strategy",
//     totalBudget: "totalBudget",
//     startDate: "startDate",
//     endDate: "endDate",
//     tactic: "tactic",
//     premiumBidAdjustment: "premiumBidAdjustment",
//     having_targets: "having_targets",
//     servingStatus: "servingStatus",
//     account_name: "account_name",
//     impressions: "impressions",
//     clicks: "clicks",
//     avgCpc: "avgCpc",
//     cost: "cost",
//     ctr: "ctr",
//     attributedConversions30d: "attributedConversions30d",
//     attributedSales30d: "attributedSales30d",
//     roas: "roas",
//     attributedConversions30dSameSKU: "attributedConversions30dSameSKU",
//     attributedSales30dSameSKU: "attributedSales30dSameSKU",
//     acos: "acos",
//     aov: "aov",
//     cpa: "cpa",
//     conversionRate: "conversionRate",
//     attributedUnitsOrdered30d: "attributedUnitsOrdered30d",
//     attributedConversions1d: "attributedConversions1d",
//     attributedSales1d: "attributedSales1d",
//     aov1d: "aov1d",
//     cpa1d: "cpa1d",
//     conversionRate1d: "conversionRate1d",
//     roas1d: "roas1d",
//     acos1d: "acos1d",
//     attributedConversions1dSameSKU: "attributedConversions1dSameSKU",
//     attributedSales1dSameSKU: "attributedSales1dSameSKU",
//     attributedUnitsOrdered1d: "attributedUnitsOrdered1d",
//     attributedConversions7d: "attributedConversions7d",
//     attributedSales7d: "attributedSales7d",
//     aov7d: "aov7d",
//     cpa7d: "cpa7d",
//     conversionRate7d: "conversionRate7d",
//     roas7d: "roas7d",
//     acos7d: "acos7d",
//     attributedConversions7dSameSKU: "attributedConversions7dSameSKU",
//     attributedSales7dSameSKU: "attributedSales7dSameSKU",
//     attributedUnitsOrdered7d: "attributedUnitsOrdered7d",
//     attributedUnitsOrderedNewToBrand14d: "attributedUnitsOrderedNewToBrand14d",
//     attributedSalesNewToBrandPercentage14d:
//       "attributedSalesNewToBrandPercentage14d",
//     attributedSalesNewToBrand14d: "attributedSalesNewToBrand14d",
//     attributedOrderRateNewToBrand14d: "attributedOrderRateNewToBrand14d",
//     attributedOrdersNewToBrandPercentage14d:
//       "attributedOrdersNewToBrandPercentage14d",
//     attributedOrdersNewToBrand14d: "attributedOrdersNewToBrand14d",
//     attributedDetailPageViewsClicks14d: "attributedDetailPageViewsClicks14d",
//     attributedConversions14d: "attributedConversions14d",
//     attributedConversions14dSameSKU: "attributedConversions14dSameSKU",
//     attributedSales14d: "attributedSales14d",
//     attributedSales14dSameSKU: "attributedSales14dSameSKU",
//     attributedUnitsOrdered14d: "attributedUnitsOrdered14d",
//     Date: "Date",
//     report_date: "report_date",
//     isExpired: "isExpired",
//   },
// ];

export const COLUMNS = [
  { name: null, field: "id" },
  { name: null, field: "selectable" },
  { name: null, field: "oo" },
  /* Default Columns */
  {
    name: "LineItem Name",
    field: "name",
    minWidth: "300px",
    format: "TextCell",
    fixed: true,
    group: "LineItems",
  },
  {
    name: "LineItem ID",
    field: "lineItemId",
    minWidth: "auto",
    format: "TextCell",
    fixed: false,
    group: "LineItems",
  },
  {
    name: "LineItem Flight Start Date",
    field: "startDateTime",
    minWidth: "auto",
    format: "DateCell",
    fixed: false,
    group: "LineItems",
  },
  {
    name: "LineItem Flight End Date",
    field: "endDateTime",
    minWidth: "auto",
    format: "DateCell",
    fixed: false,
    group: "LineItems",
  },
  {
    name: "Order Name",
    field: "campaignName",
    minWidth: "160px",
    format: "TextCell",
    fixed: false,
    group: "Orders",
  },
  {
    name: "Order ID",
    field: "campaignId",
    minWidth: "auto",
    format: "TextCell",
    fixed: false,
    group: "Orders",
  },
  {
    name: "Order Flight Start Date",
    field: "campaignStartDate",
    minWidth: "auto",
    format: "DateCell",
    fixed: false,
    group: "Orders",
  },
  {
    name: "Order Flight End Date",
    field: "campaignEndDate",
    minWidth: "auto",
    format: "DateCell",
    fixed: false,
    group: "Orders",
  },

  {
    name: "Budget",
    field: "budgetAmount",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "LineItems",
    graph: false,
  },
  {
    name: "Delivery Rate",
    field: "deliveryRate",
    minWidth: "auto",
    format: "ProgressCell",
    fixed: false,
    group: "LineItems",
  },
  {
    name: "Lifetime Cost",
    field: "totalCostLifetime",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "LineItems",
  },
  {
    name: "Advertiser Country",
    field: "advertiserCountry",
    minWidth: "auto",
    format: "TextCell",
    fixed: false,
    group: "Advertiser",
  },
  {
    name: "Advertiser Name",
    field: "advertiserName",
    minWidth: "auto",
    format: "TextCell",
    fixed: false,
    group: "Advertiser",
  },
  {
    name: "Advertiser ID",
    field: "advertiserId",
    minWidth: "auto",
    format: "TextCell",
    fixed: false,
    group: "Advertiser",
  },
  {
    name: "AdGroup Legacy Id",
    field: "adgroupLegacyId",
    minWidth: "auto",
    format: "TextCell",
    fixed: false,
  },

  /*
  { name: 'Budget Delivery Profile',                 field: 'budgetDeliveryProfile',             minWidth: 'auto', format: 'TextCell',      fixed: false },
  { name: 'Budget Catchup Boost',                    field: 'budgetCatchupBoost',                minWidth: 'auto', format: 'CurrencyCell',  fixed: false },
   */

  {
    name: "Total Cost",
    field: "totalCost",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "Sales",
    field: "salesUsd",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "ROAS",
    field: "roas",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "ACoS",
    field: "acos",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Impressions",
    field: "impressions",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "CTR",
    field: "ctr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "DPV",
    field: "dpv",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "% Of Purchases NTB",
    field: "percentOfPurchasesNewToBrand",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Sales",
    field: "totalSalesUsd",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total ROAS",
    field: "totalRoas",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total ACoS",
    field: "totalAcos",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total % Of Purchases NTB",
    field: "totalPercentOfPurchasesNewToBrand",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },

  /* Other Columns */
  {
    name: "Accept Clicks",
    field: "acceptClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Accept Cvr",
    field: "acceptCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Accept Views",
    field: "acceptViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Agency Fee",
    field: "agencyFee",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "Amazon Audience Fee",
    field: "amazonAudienceFee",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "Amazon Platform Fee",
    field: "amazonPlatformFee",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "Application",
    field: "application",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Application Clicks",
    field: "applicationClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Application CVR",
    field: "applicationCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Application Views",
    field: "applicationViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATC",
    field: "atc",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATC Clicks",
    field: "atcClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATC Views",
    field: "atcViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATCR",
    field: "atcr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "ATL",
    field: "atl",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATL Clicks",
    field: "atlClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATL Views",
    field: "atlViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ATLR",
    field: "atlr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Avg CPC",
    field: "avgCpc",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "Banner Interaction",
    field: "bannerInteraction",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Banner Interaction Clicks",
    field: "bannerInteractionClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Banner Interaction CVR",
    field: "bannerInteractionCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Banner Interaction Views",
    field: "bannerInteractionViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Clicks",
    field: "clickThroughs",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Click On Redirect",
    field: "clickOnRedirect",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Click On Redirect Clicks",
    field: "clickOnRedirectClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Click On Redirect CVR",
    field: "clickOnRedirectCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Click On Redirect Views",
    field: "clickOnRedirectViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Conv Rate",
    field: "convRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Decline Clicks",
    field: "declineClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Decline CVR",
    field: "declineCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Decline Views",
    field: "declineViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Downloaded Video Play Rate",
    field: "downloadedVideoPlayRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Downloaded Video Plays",
    field: "downloadedVideoPlays",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Downloaded Video Plays Clicks",
    field: "downloadedVideoPlaysClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Downloaded Video Plays Views",
    field: "downloadedVideoPlaysViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "DPV Clicks",
    field: "dpvClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "DPV Views",
    field: "dpvViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "DPVR",
    field: "dpvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "ECPM",
    field: "ecpm",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "eCPATC",
    field: "ecpatc",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "eCPC",
    field: "ecpc",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "eCPDPV",
    field: "ecpdpv",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "eCPP",
    field: "ecpp",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "eCPPRPV",
    field: "ecpprpv",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
  },
  {
    name: "Email Interaction",
    field: "emailInteraction",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Email Interaction Clicks",
    field: "emailInteractionClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Email Interaction Cvr",
    field: "emailInteractionCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Email Interaction Views",
    field: "emailInteractionViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Email Load",
    field: "emailLoad",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Email Load Clicks",
    field: "emailLoadClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "Email Load Cvr",
    field: "emailLoadCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Email Load Views",
    field: "emailLoadViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "ERPM",
    field: "erpm",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "Game Interaction",
    field: "gameInteraction",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Interaction Clicks",
    field: "gameInteractionClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Interaction CVR",
    field: "gameInteractionCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Interaction Views",
    field: "gameInteractionViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Load",
    field: "gameLoad",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Load Clicks",
    field: "gameLoadClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Load CVR",
    field: "gameLoadCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Game Load Views",
    field: "gameLoadViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Homepage Visit",
    field: "homepageVisit",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Homepage Visit Clicks",
    field: "homepageVisitClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Homepage Visit CPA",
    field: "homepageVisitCpa",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Homepage Visit CVR",
    field: "homepageVisitCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Homepage Visit Views",
    field: "homepageVisitViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Marketing Landing Page",
    field: "marketingLandingPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Marketing Landing Page Clicks",
    field: "marketingLandingPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Marketing Landing Page CVR",
    field: "marketingLandingPageCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Marketing Landing Page Views",
    field: "marketingLandingPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Message Sent",
    field: "messageSent",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Message Sent Clicks",
    field: "messageSentClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Message Sent CVR",
    field: "messageSentCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Message Sent Views",
    field: "messageSentViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Mobile App First Start Clicks",
    field: "mobileAppFirstStartClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Mobile App First Start CVR",
    field: "mobileAppFirstStartCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Mobile App First Start Views",
    field: "mobileAppFirstStartViews",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Mobile App First Starts",
    field: "mobileAppFirstStarts",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB ECPP",
    field: "newToBrandEcpp",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB ERPM",
    field: "newToBrandErpm",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB Product Sales",
    field: "newToBrandProductSalesUsd",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB Purchase Rate",
    field: "newToBrandPurchaseRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB Purchases",
    field: "newToBrandPurchases",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB Purchases Clicks",
    field: "newToBrandPurchasesClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB Purchases Views",
    field: "newToBrandPurchasesViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB ROAS",
    field: "newToBrandRoas",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "NTB Units Sold",
    field: "newToBrandUnitsSold",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "PRPV",
    field: "prpv",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "PRPV Clicks",
    field: "prpvClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "PRPV Views",
    field: "prpvViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
  },
  {
    name: "PRPVR",
    field: "prpvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
  },
  {
    name: "Purchases",
    field: "purchases",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchase Button",
    field: "purchaseButton",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchase Button Clicks",
    field: "purchaseButtonClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchase Button CVR",
    field: "purchaseButtonCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchase Button Views",
    field: "purchaseButtonViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchase Rate",
    field: "purchaseRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchases Clicks",
    field: "purchasesClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Purchases Views",
    field: "purchasesViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Referral",
    field: "referral",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Referral Clicks",
    field: "referralClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Referral CVR",
    field: "referralCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Referral Views",
    field: "referralViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Confirm Page",
    field: "registrationConfirmPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Confirm Page Clicks",
    field: "registrationConfirmPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Confirm Page CVR",
    field: "registrationConfirmPageCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Confirm Page Views",
    field: "registrationConfirmPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Form",
    field: "registrationForm",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Form Clicks",
    field: "registrationFormClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Form CVR",
    field: "registrationFormCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Registration Form Views",
    field: "registrationFormViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Rental Rate",
    field: "rentalRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Rentals",
    field: "rentals",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Rentals Clicks",
    field: "rentalsClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Rentals Views",
    field: "rentalsViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Button",
    field: "signupButton",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Button Clicks",
    field: "signupButtonClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Button CVR",
    field: "signupButtonCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Button Views",
    field: "signupButtonViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Page",
    field: "signupPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Page Clicks",
    field: "signupPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Page CVR",
    field: "signupPageCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Signup Page Views",
    field: "signupPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "SNSS",
    field: "snss",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "SNSS Clicks",
    field: "snssClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "SNSS Views",
    field: "snssViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "SNSSR",
    field: "snssr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Store Locator Page",
    field: "storeLocatorPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Store Locator Page Clicks",
    field: "storeLocatorPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Store Locator Page CVR",
    field: "storeLocatorPageCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Store Locator Page Views",
    field: "storeLocatorPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Submit Button",
    field: "submitButton",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Submit Button Clicks",
    field: "submitButtonClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Submit Button CVR",
    field: "submitButtonCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Submit Button Views",
    field: "submitButtonViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Button",
    field: "subscriptionButton",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Button Clicks",
    field: "subscriptionButtonClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Button CVR",
    field: "subscriptionButtonCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Button Views",
    field: "subscriptionButtonViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Page",
    field: "subscriptionPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Page Clicks",
    field: "subscriptionPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Page CVR",
    field: "subscriptionPageCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Subscription Page Views",
    field: "subscriptionPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Success Page",
    field: "successPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Success Page Clicks",
    field: "successPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Success Page CVR",
    field: "successPageCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Success Page Views",
    field: "successPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Supply Cost",
    field: "supplyCost",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Finish",
    field: "surveyFinish",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Finish Clicks",
    field: "surveyFinishClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Finish CVR",
    field: "surveyFinishCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Finish Views",
    field: "surveyFinishViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Start",
    field: "surveyStart",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Start Clicks",
    field: "surveyStartClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Start CVR",
    field: "surveyStartCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Survey Start Views",
    field: "surveyStartViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Thank You Page",
    field: "thankYouPage",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Thank You Page Clicks",
    field: "thankYouPageClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Thank You Page CVR",
    field: "thankYouPageCvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Thank You Page Views",
    field: "thankYouPageViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total eCPP",
    field: "totalEcpp",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "Total eCPPRPV",
    field: "totalEcpprpv",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "Total eRPM",
    field: "totalErpm",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "Total Fee",
    field: "totalFee",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Advertising",
  },
  {
    name: "Total NTB eCPP",
    field: "totalNewToBrandEcpp",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB eRPM",
    field: "totalNewToBrandErpm",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB Product Sales",
    field: "totalNewToBrandProductSalesUsd",
    minWidth: "auto",
    format: "CurrencyCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB Purchase Rate",
    field: "totalNewToBrandPurchaseRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB Purchases",
    field: "totalNewToBrandPurchases",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB Purchases Clicks",
    field: "totalNewToBrandPurchasesClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB Purchases Views",
    field: "totalNewToBrandPurchasesViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB ROAS",
    field: "totalNewToBrandRoas",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total NTB Units Sold",
    field: "totalNewToBrandUnitsSold",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Pixel",
    field: "totalPixel",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Pixel CPA",
    field: "totalPixelCpa",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Pixel CVR",
    field: "totalPixelCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Pixel Views",
    field: "totalPixelViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Pixels Clicks",
    field: "totalPixelsClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total PRPV",
    field: "totalPrpv",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total PRPV Clicks",
    field: "totalPrpvClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total PRPV Views",
    field: "totalPrpvViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total PRPVR",
    field: "totalPrpvr",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Purchase Rate",
    field: "totalPurchaseRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Purchases",
    field: "totalPurchases",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Purchases Clicks",
    field: "totalPurchasesClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Purchases Views",
    field: "totalPurchasesViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Total Units Sold",
    field: "totalUnitsSold",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Units Sold",
    field: "unitsSold",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Complete",
    field: "videoComplete",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Download Rate",
    field: "videoDownloadRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Downloads",
    field: "videoDownloads",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Downloads Clicks",
    field: "videoDownloadsClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Downloads Views",
    field: "videoDownloadsViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video First Quartile",
    field: "videoFirstQuartile",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Midpoint",
    field: "videoMidpoint",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Mute",
    field: "videoMute",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Pause",
    field: "videoPause",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Resume",
    field: "videoResume",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Start",
    field: "videoStart",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Started",
    field: "videoStarted",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Started Views",
    field: "videoStartedViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Streams",
    field: "videoStreams",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Streams Clicks",
    field: "videoStreamsClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Streams Rate",
    field: "videoStreamsRate",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Streams Views",
    field: "videoStreamsViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Third Quartile",
    field: "videoThirdQuartile",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Video Unmute",
    field: "videoUnmute",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Interaction",
    field: "widgetInteraction",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Interaction Clicks",
    field: "widgetInteractionClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Interaction Cvr",
    field: "widgetInteractionCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Interaction Views",
    field: "widgetInteractionViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Load",
    field: "widgetLoad",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Load Clicks",
    field: "widgetLoadClicks",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Load CVR",
    field: "widgetLoadCvr",
    minWidth: "auto",
    format: "PercentCell",
    fixed: false,
    group: "Conversions",
  },
  {
    name: "Widget Load Views",
    field: "widgetLoadViews",
    minWidth: "auto",
    format: "NumberCell",
    fixed: false,
    group: "Conversions",
  },

  {
    name: "Labels",
    field: "labels",
    minWidth: "auto",
    format: "LabelCell",
    fixed: false,
    group: "-",
  },
];

export const EMPTY_TABLE_MESSAGE =
  "There are no LineItems set up for this account.";
